services:
  app:
    image: fastapi-analytics-microservice:dev
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - PORT=8002
    #   - DATA_BASE_URL=${DATA_BASE_URL}
    env_file:
      - .env.compose
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/app:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker-compose.yml
    depends_on:
      timescale_pg_db:
        condition: service_healthy

  timescale_pg_db:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    expose:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - timescale_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  timescale_db_data: