"""Adding some extra columns to EventModel table

Revision ID: 6069c5dd3ea9
Revises: c20440609c10
Create Date: 2025-04-28 17:04:14.518914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6069c5dd3ea9'
down_revision: Union[str, None] = 'c20440609c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventmodel', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eventmodel', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eventmodel', sa.Column('referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eventmodel', sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eventmodel', sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('eventmodel_time_idx', table_name='eventmodel')
    op.create_index(op.f('ix_eventmodel_ip_address'), 'eventmodel', ['ip_address'], unique=False)
    op.create_index(op.f('ix_eventmodel_referrer'), 'eventmodel', ['referrer'], unique=False)
    op.create_index(op.f('ix_eventmodel_session_id'), 'eventmodel', ['session_id'], unique=False)
    op.create_index(op.f('ix_eventmodel_user_agent'), 'eventmodel', ['user_agent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventmodel_user_agent'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_session_id'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_referrer'), table_name='eventmodel')
    op.drop_index(op.f('ix_eventmodel_ip_address'), table_name='eventmodel')
    op.create_index('eventmodel_time_idx', 'eventmodel', [sa.literal_column('time DESC')], unique=False)
    op.drop_column('eventmodel', 'duration')
    op.drop_column('eventmodel', 'session_id')
    op.drop_column('eventmodel', 'referrer')
    op.drop_column('eventmodel', 'user_agent')
    op.drop_column('eventmodel', 'ip_address')
    # ### end Alembic commands ###
